SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Controllers/OnReadingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SkolskaBibliotekaDBContext;

namespace SkolskaBiblioteka.Areas.Admin.Controllers
{
    [AdminAuth]
    public class OnReadingController : Controller
    {
        SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel();

        // GET: Admin/OnReading
        public ActionResult Index(int? p)
        {
            var na_citanju = db.Na_Citanju.OrderByDescending(n => n.Na_CitanjuID);
            if (p <= 0) p = 1;

            ViewBag.PageSize = 10;
            ViewBag.PageNumber = (p ?? 1);
            ViewBag.PageCount = na_citanju.ToPagedList((int)ViewBag.PageNumber, (int)ViewBag.PageSize).PageCount;
            ViewBag.HasPrevious = ((p ?? 1) != 1);
            ViewBag.HasNext = ((p ?? 1) != (int)ViewBag.PageCount);

            return View(na_citanju.ToPagedList((int)ViewBag.PageNumber, (int)ViewBag.PageSize).ToList());
        }

        // GET: Admin/OnReading/Late
        public ActionResult Late(int? p)
        {
            var na_citanju = db.Na_Citanju.OrderByDescending(n => n.Na_CitanjuID).Where(nc => nc.DatumVracanja == null && nc.RokZaVracanje < DateTime.Now);
            if (p <= 0) p = 1;

            ViewBag.PageSize = 10;
            ViewBag.PageNumber = (p ?? 1);
            ViewBag.PageCount = na_citanju.ToPagedList((int)ViewBag.PageNumber, (int)ViewBag.PageSize).PageCount;
            ViewBag.HasPrevious = ((p ?? 1) != 1);
            ViewBag.HasNext = ((p ?? 1) != (int)ViewBag.PageCount);

            return View(na_citanju.ToPagedList((int)ViewBag.PageNumber, (int)ViewBag.PageSize).ToList());
        }

        public ActionResult Search(int? p, string username)
        {
            var na_citanju = db.Na_Citanju.Where(n => n.Korisnik.Username.ToLower() == username.ToLower()).OrderByDescending(n => n.Na_CitanjuID);
            if (p <= 0) p = 1;

            ViewBag.PageSize = 10;
            ViewBag.PageNumber = (p ?? 1);
            ViewBag.PageCount = na_citanju.ToPagedList((int)ViewBag.PageNumber, (int)ViewBag.PageSize).PageCount;
            ViewBag.HasPrevious = ((p ?? 1) != 1);
            ViewBag.HasNext = ((p ?? 1) != (int)ViewBag.PageCount);

            return View(na_citanju.ToPagedList((int)ViewBag.PageNumber, (int)ViewBag.PageSize).ToList());
        }

        // GET: Admin/OnReading/Details/5
        public ActionResult Details(int id)
        {
            Na_Citanju nc = db.Na_Citanju.FirstOrDefault(n => n.Na_CitanjuID == id);

            return View(nc);
        }

        [HttpPost]
        public ActionResult Return(int id)
        {
            Na_Citanju nc = db.Na_Citanju.FirstOrDefault(n => n.Na_CitanjuID == id);
            if(nc != null)
            {
                if (nc.DatumVracanja == null)
                {
                    nc.DatumVracanja = DateTime.Now;
                    nc.Primerak.Aktivna = true;

                    db.SaveChanges();
                }
            }

            return RedirectToAction("Index");
        }

        // POST: Admin/OnReading/Create
        [HttpPost]
        public ActionResult Create(int? primerakId, string username)
        {
            try
            {
                if(primerakId != null && username != null)
                {
                    Primerak pr = db.Primerak.FirstOrDefault(p => p.PrimerakID == primerakId);
                    Korisnik kor = db.Korisnik.FirstOrDefault(k => k.Username == username);

                    if (pr != null && kor != null)
                    {
                        if(pr.Aktivna == false)
                        {
                            if(kor.Rezervacije.FirstOrDefault(x=>x.PrimerakID==primerakId)==null)
                                return RedirectToAction("Index");
                        }

                        pr.Aktivna = false;

                        Na_Citanju nc = new Na_Citanju();
                        nc.KorisnikID = kor.KorisnikID;
                        nc.PrimerakID = pr.PrimerakID;
                        nc.DatumUzimanja = DateTime.Now;
                        nc.RokZaVracanje = DateTime.Now.AddDays(21);

                        var rez = db.Rezervacije.FirstOrDefault(x => x.Korisnik.Username == username && x.PrimerakID == primerakId);
                        if (rez != null)
                        {
                            rez.Validna = false;
                        }

                        db.Na_Citanju.Add(nc);
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/OnReading/Edit/5
        public ActionResult Edit(int id)
        {
            Na_Citanju nc = db.Na_Citanju.FirstOrDefault(n => n.Na_CitanjuID == id);
            ViewBag.Primerci = db.Primerak.Where(p => p.KnjigaID == nc.Primerak.KnjigaID).Select(f => new SelectListItem { Value = f.PrimerakID.ToString(), Text = f.InventarskiBroj + " - " + f.Povezi.Naziv }).ToList();
            ViewBag.Korisnici = db.Korisnik.OrderBy(k => k.Prezime).Select(f => new SelectListItem { Value = f.KorisnikID.ToString(), Text = f.Ime + " - " + f.Prezime }).ToList();

            return View(nc);
        }

        // POST: Admin/OnReading/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Na_Citanju nc)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    Na_Citanju na = db.Na_Citanju.FirstOrDefault(n => n.Na_CitanjuID == id);
                    if(na != null)
                    {
                        na.KorisnikID = nc.KorisnikID;
                        na.PrimerakID = nc.PrimerakID;
                        na.RokZaVracanje = nc.RokZaVracanje;
                        na.DatumUzimanja = nc.DatumUzimanja;
                        na.DatumVracanja = nc.DatumVracanja;

                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/OnReading/Delete/5
        public ActionResult Delete(int id)
        {
            Na_Citanju nc = db.Na_Citanju.FirstOrDefault(n => n.Na_CitanjuID == id);

            return View(nc);
        }

        // POST: Admin/OnReading/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                Na_Citanju nc = db.Na_Citanju.FirstOrDefault(n => n.Na_CitanjuID == id);
                if(nc != null)
                {
                    db.Na_Citanju.Remove(nc);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SkolskaBiblioteka/SkolskaBiblioteka/Controllers/SearchController.cs
using SkolskaBiblioteka.ViewModels;
using SkolskaBibliotekaDBContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SkolskaBiblioteka.Models;

namespace SkolskaBiblioteka.Controllers
{
    [LoadAuth]
    public class SearchController : Controller
    {
        // GET: Search
        [HttpGet]
        public ActionResult Index(string sortOrder, int? page, string NameString, string AutorString, string IzdavacString, string ZanrString, int? GodinaInt, string Izdanje)
        {
            try
            {

                ViewBag.Naslov = NameString;
                ViewBag.ImeAutora = AutorString;
                ViewBag.ImeIzdavaca = IzdavacString;
                ViewBag.Signatura = ZanrString;
                ViewBag.PapirnoIzdanje = Izdanje;
                ViewBag.GodinaIzanja = GodinaInt;


                if (String.IsNullOrEmpty(sortOrder))
                {
                    sortOrder = "Name";
                }
                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = sortOrder == "Name" ? "name_desc" : "Name";
                ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
                ViewBag.IzdavacSortParm = sortOrder == "Izdavac" ? "izdavac_desc" : "Izdavac";
                ViewBag.ZanrSortParm = sortOrder == "Zanr" ? "zanr_desc" : "Zanr";
                ViewBag.PapirSortParm = sortOrder == "Papir" ? "papir_desc" : "Papir";

                using (SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel())
                {
                    var knjige = from s in db.Knjiga
                                 select s;
                    switch (sortOrder)
                    {
                        case "Name":
                            knjige = knjige.OrderBy(x => x.Naziv);
                            break;
                        case "name_desc":
                            knjige = knjige.OrderByDescending(s => s.Naziv);
                            break;
                        case "Date":
                            knjige = knjige.OrderBy(s => s.DatumIzdavanja);
                            break;
                        case "date_desc":
                            knjige = knjige.OrderByDescending(s => s.DatumIzdavanja);
                            break;
                        case "Izdavac":
                            knjige = knjige.OrderBy(s => s.Izdavac.Naziv);
                            break;
                        case "izdavac_desc":
                            knjige = knjige.OrderByDescending(s => s.Izdavac.Naziv);
                            break;
                        case "Zanr":
                            knjige = knjige.OrderBy(s => s.Signatura.Naziv);
                            break;
                        case "zanr_desc":
                            knjige = knjige.OrderByDescending(s => s.Signatura.Naziv);
                            break;
                        case "Papir":
                            knjige = knjige.OrderBy(s => s.PapirnoIzdanje);
                            break;
                        case "papir_desc":
                            knjige = knjige.OrderByDescending(s => s.PapirnoIzdanje);
                            break;
                    }


                    if (!String.IsNullOrWhiteSpace(NameString))
                    {
                        knjige = knjige.Where(x => x.Naziv.ToUpper().Contains(NameString.ToUpper()));
                    }
                    if (!String.IsNullOrWhiteSpace(IzdavacString))
                    {
                        knjige = knjige.Where(x => x.Izdavac.Naziv.ToUpper().Contains(IzdavacString.ToUpper()));
                    }
                    if (!String.IsNullOrWhiteSpace(ZanrString))
                    {
                        knjige = knjige.Where(x => x.Signatura.Naziv.ToUpper().Contains(ZanrString.ToUpper()));
                    }

                    if (Izdanje == "Papirno")
                    {
                        knjige = knjige.Where(x => x.PapirnoIzdanje == true);
                    }
                    else
                    {
                        if (Izdanje == "Elektronsko")
                        {
                            knjige = knjige.Where(x => x.PapirnoIzdanje == false);
                        }
                    }

                    if (GodinaInt != null)
                    {
                        if (ViewBag.GodinaIzanja > 0)
                            knjige = knjige.Where(x => x.DatumIzdavanja.Value.Year == GodinaInt);
                    }

                    var Knjige = knjige.ToList();

                    if (!String.IsNullOrWhiteSpace(AutorString))
                    {

                        Knjige = Knjige.Where(x => Contains(x.Autor.ToList(), AutorString.ToUpper())).ToList();
                    }


                    List<KnjigaZaPrikaz> KnjigeZaPrikaz = new List<KnjigaZaPrikaz>();

                    //if (Knjige.Count != 0)
                    //    foreach (Knjiga k in Knjige)
                    //    {
                    //        if (k != null)
                    //            KnjigeZaPrikaz.Add(new KnjigaZaPrikaz(k));
                    //    }

                    Knjige.ForEach(x => { if (x != null) KnjigeZaPrikaz.Add(new KnjigaZaPrikaz(x)); });

                    int pageSize = 20;
                    int pageNumber = (page ?? 1);



                    return View(KnjigeZaPrikaz.ToPagedList(pageNumber, pageSize));
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("_Error");
            }
        }

        public ActionResult Search(string sortOrder, int? page, string NameString, string AutorString, string IzdavacString, string ZanrString, int? GodinaInt, string Izdanje)
        {
            try
            {

                ViewBag.Naslov = NameString;
                ViewBag.ImeAutora = AutorString;
                ViewBag.ImeIzdavaca = IzdavacString;
                ViewBag.Signatura = ZanrString;
                ViewBag.PapirnoIzdanje = Izdanje;
                ViewBag.GodinaIzanja = GodinaInt;


                if (String.IsNullOrEmpty(sortOrder))
                {
                    sortOrder = "Name";
                }
                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = sortOrder == "Name" ? "name_desc" : "Name";
                ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
                ViewBag.IzdavacSortParm = sortOrder == "Izdavac" ? "izdavac_desc" : "Izdavac";
                ViewBag.ZanrSortParm = sortOrder == "Zanr" ? "zanr_desc" : "Zanr";
                ViewBag.PapirSortParm = sortOrder == "Papir" ? "papir_desc" : "Papir";

                using (SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel())
                {
                    var knjige = from s in db.Knjiga
                                 select s;
                    switch (sortOrder)
                    {
                        case "Name":
                            knjige = knjige.OrderBy(x => x.Naziv);
                            break;
                        case "name_desc":
                            knjige = knjige.OrderByDescending(s => s.Naziv);
                            break;
                        case "Date":
                            knjige = knjige.OrderBy(s => s.DatumIzdavanja);
                            break;
                        case "date_desc":
                            knjige = knjige.OrderByDescending(s => s.DatumIzdavanja);
                            break;
                        case "Izdavac":
                            knjige = knjige.OrderBy(s => s.Izdavac.Naziv);
                            break;
                        case "izdavac_desc":
                            knjige = knjige.OrderByDescending(s => s.Izdavac.Naziv);
                            break;
                        case "Zanr":
                            knjige = knjige.OrderBy(s => s.Signatura.Naziv);
                            break;
                        case "zanr_desc":
                            knjige = knjige.OrderByDescending(s => s.Signatura.Naziv);
                            break;
                        case "Papir":
                            knjige = knjige.OrderBy(s => s.PapirnoIzdanje);
                            break;
                        case "papir_desc":
                            knjige = knjige.OrderByDescending(s => s.PapirnoIzdanje);
                            break;
                    }


                    if (!String.IsNullOrWhiteSpace(NameString))
                    {
                        knjige = knjige.Where(x => x.Naziv.ToUpper().Contains(NameString.ToUpper()));
                    }
                    if (!String.IsNullOrWhiteSpace(IzdavacString))
                    {
                        knjige = knjige.Where(x => x.Izdavac.Naziv.ToUpper().Contains(IzdavacString.ToUpper()));
                    }
                    if (!String.IsNullOrWhiteSpace(ZanrString))
                    {
                        knjige = knjige.Where(x => x.Signatura.Naziv.ToUpper().Contains(ZanrString.ToUpper()));
                    }

                    if (Izdanje == "Papirno")
                    {
                        knjige = knjige.Where(x => x.PapirnoIzdanje == true);
                    }
                    else
                    {
                        if (Izdanje == "Elektronsko")
                        {
                            knjige = knjige.Where(x => x.PapirnoIzdanje == false);
                        }
                    }

                    if (GodinaInt != null)
                    {
                        if (ViewBag.GodinaIzanja > 0)

SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Views/OnReading/Details.cshtml
@model SkolskaBibliotekaDBContext.Na_Citanju

@{
    ViewBag.Title = "На читању - Детаљи";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">На читању - Детаљи</h1>
    </div>
</div>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Korisnik.MaticniBroj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Korisnik.MaticniBroj)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Primerak.InventarskiBroj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Primerak.InventarskiBroj)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumUzimanja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumUzimanja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumVracanja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumVracanja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RokZaVracanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RokZaVracanje)
        </dd>
    </dl>
</div>

@if (Model.DatumVracanja == null)
{
    using (Html.BeginForm("Return", "OnReading", FormMethod.Post))
    {
        @Html.Hidden("id", Model.Na_CitanjuID)
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"><button type="submit" class="btn btn-primary">Врати књигу</button></h1>
            </div>
        </div>
    }
}

<p>
    @Html.ActionLink("Измени", "Edit", new { id = Model.Na_CitanjuID }) |
    @Html.ActionLink("Назад на листу", "Index")
</p>

SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Views/OnReading/Index.cshtml
@model IEnumerable<SkolskaBibliotekaDBContext.Na_Citanju>

@{
    ViewBag.Title = "На читању - Све";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">На читању - Све</h1>
    </div>
</div>

@using (Html.BeginForm("Search", "OnReading", FormMethod.Get, new { @class = "form-inline" }))
{
    <div class="form-group">
        <label for="x">Корисник</label>
        @Html.TextBox("username", "", new { @class = "form-control", @placeholder = "user213" })
    </div>
    <button type="submit" class="btn btn-default">Нађи</button>
}

<br />
<div style="overflow:auto;">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KorisnikID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Primerak.InventarskiBroj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumUzimanja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumVracanja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RokZaVracanje)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            string klasa = "";
            if (item.DatumVracanja == null)
            {
                if (item.RokZaVracanje == null)
                {
                    klasa = "";
                }
                else
                {
                    if (item.RokZaVracanje < DateTime.Now)
                    {
                        klasa = "overdue";
                    }
                    else
                    {
                        if ((DateTime.Now - item.RokZaVracanje).Value.Days <= 3)
                        {
                            klasa = "almost-overdue";
                        }
                        else
                        {
                            klasa = "ontime";
                        }
                    }
                }
            }
            else
            {
                klasa = "ontime";
            }

            <tr class="@klasa">
                <td>
                    <a href="@Url.Action("Details", "User", new { area = "Admin", id = item.KorisnikID })">
                        @Html.DisplayFor(modelItem => item.Korisnik.Username)
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Details", "Copy", new { area = "Admin", id = item.PrimerakID })">
                        @Html.DisplayFor(modelItem => item.Primerak.InventarskiBroj)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumUzimanja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumVracanja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RokZaVracanje)
                </td>
                <td>
                    @Html.ActionLink("Измени", "Edit", new { id = item.Na_CitanjuID }) |
                    @Html.ActionLink("Детаљи", "Details", new { id = item.Na_CitanjuID }) |
                    @Html.ActionLink("Обриши", "Delete", new { id = item.Na_CitanjuID })
                </td>
            </tr>
        }

    </table>
</div>
<nav>
    <ul class="pagination">
        <li class="@((ViewBag.HasPrevious) ? "" : "disabled")">
            <a href="@Url.Action("Index", "OnReading", new { area = "Admin" })?p=@(ViewBag.PageNumber-1)" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        @for (var i = 1; i <= ViewBag.PageCount; i++)
            {
                if (ViewBag.PageNumber == i)
                {
                <li class="active"><a href="@Url.Action("Index", "OnReading", new { area = "Admin" })?p=@i">@i <span class="sr-only">(current)</span></a></li>
            }
            else
            {
                <li><a href="@Url.Action("Index", "OnReading", new { area = "Admin" })?p=@i">@i</a></li>
            }
        }
        <li class="@((ViewBag.HasNext) ? "" : "disabled")">
            <a href="@Url.Action("Index", "OnReading", new { area = "Admin" })?p=@(ViewBag.PageNumber-1)" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Views/OnReading/Late.cshtml
@model IEnumerable<SkolskaBibliotekaDBContext.Na_Citanju>

@{
    ViewBag.Title = "На читању - Све";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">На читању - Кашњења</h1>
    </div>
</div>
<div style="overflow:auto;">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KorisnikID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Primerak.InventarskiBroj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumUzimanja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumVracanja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RokZaVracanje)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="overdue">
                <td>
                    <a href="@Url.Action("Details", "User", new { area = "Admin", id = item.KorisnikID })">
                        @Html.DisplayFor(modelItem => item.Korisnik.Username)
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Details", "Copy", new { area = "Admin", id = item.PrimerakID })">
                        @Html.DisplayFor(modelItem => item.Primerak.InventarskiBroj)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumUzimanja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumVracanja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RokZaVracanje)
                </td>
                <td>
                    @Html.ActionLink("Измени", "Edit", new { id = item.Na_CitanjuID }) |
                    @Html.ActionLink("Детаљи", "Details", new { id = item.Na_CitanjuID }) |
                    @Html.ActionLink("Обриши", "Delete", new { id = item.Na_CitanjuID })
                </td>
            </tr>
        }

    </table>
</div>
<nav>
    <ul class="pagination">
        <li class="@((ViewBag.HasPrevious) ? "" : "disabled")">
            <a href="@Url.Action("Late", "OnReading", new { area = "Admin" })?p=@(ViewBag.PageNumber-1)" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        @for (var i = 1; i <= ViewBag.PageCount; i++)
            {
                if (ViewBag.PageNumber == i)
                {
                <li class="active"><a href="@Url.Action("Late", "OnReading", new { area = "Admin" })?p=@i">@i <span class="sr-only">(current)</span></a></li>
            }
            else
            {
                <li><a href="@Url.Action("Late", "OnReading", new { area = "Admin" })?p=@i">@i</a></li>
            }
        }
        <li class="@((ViewBag.HasNext) ? "" : "disabled")">
            <a href="@Url.Action("Late", "OnReading", new { area = "Admin" })?p=@(ViewBag.PageNumber-1)" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Views/OnReading/Search.cshtml
@model IEnumerable<SkolskaBibliotekaDBContext.Na_Citanju>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">На читању - Све</h1>
    </div>
</div>

@using (Html.BeginForm("Search", "OnReading", FormMethod.Get, new { @class = "form-inline" }))
{
    <div class="form-group">
        <label for="x">Корисник</label>
        @Html.TextBox("username", "", new { @class = "form-control", @placeholder = "user213" })
    </div>
    <button type="submit" class="btn btn-default">Нађи</button>
}

<br />
<div style="overflow:auto;">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KorisnikID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Primerak.InventarskiBroj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumUzimanja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumVracanja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RokZaVracanje)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            string klasa = "";
            if (item.DatumVracanja == null)
            {
                if (item.RokZaVracanje == null)
                {
                    klasa = "";
                }
                else
                {
                    if (item.RokZaVracanje < DateTime.Now)
                    {
                        klasa = "overdue";
                    }
                    else
                    {
                        if ((DateTime.Now - item.RokZaVracanje).Value.Days <= 3)
                        {
                            klasa = "almost-overdue";
                        }
                        else
                        {
                            klasa = "ontime";
                        }
                    }
                }
            }
            else
            {
                klasa = "ontime";
            }

            <tr class="@klasa">
                <td>
                    <a href="@Url.Action("Details", "User", new { area = "Admin", id = item.KorisnikID })">
                        @Html.DisplayFor(modelItem => item.Korisnik.Username)
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Details", "Copy", new { area = "Admin", id = item.PrimerakID })">
                        @Html.DisplayFor(modelItem => item.Primerak.InventarskiBroj)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumUzimanja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumVracanja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RokZaVracanje)
                </td>
                <td>
                    @Html.ActionLink("Измени", "Edit", new { id = item.Na_CitanjuID }) |
                    @Html.ActionLink("Детаљи", "Details", new { id = item.Na_CitanjuID }) |
                    @Html.ActionLink("Обриши", "Delete", new { id = item.Na_CitanjuID })
                </td>
            </tr>
        }

    </table>
    </div>
    <nav>
        <ul class="pagination">
            <li class="@((ViewBag.HasPrevious) ? "" : "disabled")">
                <a href="@Url.Action("Search", "OnReading", new { area = "Admin" })?p=@(ViewBag.PageNumber-1)" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for (var i = 1; i <= ViewBag.PageCount; i++)
            {
                if (ViewBag.PageNumber == i)
                {
                    <li class="active"><a href="@Url.Action("Search", "OnReading", new { area = "Admin" })?p=@i">@i <span class="sr-only">(current)</span></a></li>
                }
                else
                {
                    <li><a href="@Url.Action("Search", "OnReading", new { area = "Admin" })?p=@i">@i</a></li>
                }
            }
            <li class="@((ViewBag.HasNext) ? "" : "disabled")">
                <a href="@Url.Action("Search", "OnReading", new { area = "Admin" })?p=@(ViewBag.PageNumber-1)" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>