SkolskaBiblioteka/SkolskaBiblioteka/Controllers/LibraryController.cs
using SkolskaBiblioteka.Models;
using SkolskaBiblioteka.ViewModels;
using SkolskaBibliotekaDBContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SkolskaBiblioteka.Controllers
{
    [LoadAuth]
    [Authorize]
    public class LibraryController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
            return View(new SkolskaBibliotekaDBModel().Knjiga.ToList());
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Book(int? id)
        {
            if (id != null)
            {
                using (SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel())
                {
                    var book = db.Knjiga.FirstOrDefault(x => x.KnjigaID == id);

                    if (book != null)
                    {

                        KnjigaDetails kd = new KnjigaDetails(book, 0);
                        kd.NoviKomentar = new Komentar();
                        kd.NoviKomentar.KnjigaID = book.KnjigaID;

                        return View(kd);
                    }
                    else
                    {
                        ViewBag.Error = "Страница није пронађена.";
                        return View("_Error");
                    }
                }
            }
            else
            {
                ViewBag.Error = "Страница није пронађена.";
                return View("_Error");
            }
        }

        [HttpPost]
        public ActionResult Book(Komentar k)
        {
            using (SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel())
            {
                int korisnikId = db.Korisnik.FirstOrDefault(y => y.Username == User.Identity.Name).KorisnikID;
                k.Knjiga = db.Knjiga.FirstOrDefault(x => x.KnjigaID == k.KnjigaID);
                k.VremeKomentara = DateTime.Now;
                k.KorisnikID = korisnikId;
                k.VoteUp = 0;
                k.VoteDown = 0;
                k.Reported = false;

                db.Komentar.Add(k);
                db.SaveChanges();

                KnjigaDetails kd = new KnjigaDetails(k.Knjiga, 0);

                return PartialView("_Komentari", kd);
            }
        }

        [HttpPost]
        public ActionResult RemoveComment(int id)
        {
            using (SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel())
            {
                var kom = db.Komentar.FirstOrDefault(x => x.KomentarID == id);

                KorisnikZaPrikaz kzp = (KorisnikZaPrikaz)Session["Korisnik"];

                if (kom != null)
                {
                    if (kom.KorisnikID == kzp.KorisnikId || kzp.AccessLevels.Min() == 7)
                    {
                        var book = kom.Knjiga;

                        db.Komentar.Remove(kom);

                        KnjigaDetails kd = new KnjigaDetails(book, 0);

                        db.SaveChanges();

                        return PartialView("_Komentari", kd);
                    }
                    else
                    {
                        Response.StatusCode = (int)HttpStatusCode.BadRequest;
                        return new EmptyResult();
                    }
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return new EmptyResult();
                }
            }
        }

        [HttpPost]
        public ActionResult Reserve(int id)
        {
            using (SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel())
            {
                var rez = db.Rezervacije.Create();

                rez.KnjigaID = (int)id;
                rez.Knjiga = db.Knjiga.FirstOrDefault(x => x.KnjigaID == rez.KnjigaID);
                rez.KorisnikID = db.Korisnik.FirstOrDefault(x => x.Username == User.Identity.Name).KorisnikID;

                var primerak = db.Primerak.FirstOrDefault(x => x.Aktivna && x.KnjigaID == rez.KnjigaID);

                if (primerak != null)
                {
                    rez.PrimerakID = primerak.PrimerakID;

                    rez.Validna = true;

                    primerak.Aktivna = false;

                    rez.DatumPocetkaRezervacije = DateTime.Now;
                    rez.DatumIstekaRezervacije = DateTime.Now.AddDays(Convert.ToDouble(Podesavanja.Get("DuzinaRezervacije")));

                    db.Rezervacije.Add(rez);

                    if (ModelState.IsValid)
                        db.SaveChanges();

                    var book = db.Knjiga.FirstOrDefault(x => x.KnjigaID == id);

                    KnjigaDetails kd = new KnjigaDetails(book, 0);
                    kd.NoviKomentar = new Komentar();
                    kd.NoviKomentar.KnjigaID = book.KnjigaID;

                    return PartialView("_CommentInfo", kd);
                }
                else
                {
                    db.Rezervacije.Add(rez);

                    //DB Tasks:Dodati dnevno proveravanje knjiga i dodati valid = true ako je rezervisana knjiga vracena i datume pocetka i isteka rezervacije
                    //Ili proveravati rezervacije pri svakom vracanju knjige ili otkazu rezervacije.

                    rez.DatumPocetkaRezervacije = DateTime.Now;
                    rez.DatumIstekaRezervacije = DateTime.Now.AddDays(Convert.ToDouble(Podesavanja.Get("DuzinaRezervacijeBezKnjige")));

                    rez.Validna = true;

                    if (ModelState.IsValid)
                        db.SaveChanges();

                    var book = db.Knjiga.FirstOrDefault(x => x.KnjigaID == id);

                    KnjigaDetails kd = new KnjigaDetails(book, 0);
                    kd.NoviKomentar = new Komentar();
                    kd.NoviKomentar.KnjigaID = book.KnjigaID;

                    return PartialView("_CommentInfo", kd);
                }

            }
        }

        [HttpPost]
        public ActionResult RemoveReserve(int id)
        {

            using (SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel())
            {
                int korisnikId = db.Korisnik.FirstOrDefault(x => x.Username == User.Identity.Name).KorisnikID;

                var rezervacija = db.Rezervacije.FirstOrDefault(x => x.KorisnikID == korisnikId && x.KnjigaID == id && x.Validna == true);

                if (rezervacija != null)
                {
                    if (rezervacija.PrimerakID != null)
                    {
                        var primerak = db.Primerak.FirstOrDefault(x => x.PrimerakID == rezervacija.PrimerakID);
                        primerak.Aktivna = true;
                    }

                    db.Rezervacije.Remove(rezervacija);

                    var book = db.Knjiga.FirstOrDefault(x => x.KnjigaID == id);

                    KnjigaDetails kd = new KnjigaDetails(book, 0);
                    kd.NoviKomentar = new Komentar();
                    kd.NoviKomentar.KnjigaID = book.KnjigaID;

                    db.SaveChanges();

                    return PartialView("_CommentInfo", kd);
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return new EmptyResult();
                }
            }
        }

        [HttpPost]
        public ActionResult Download(int id)
        {
            using (SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel())
            {
                var korisnik = db.Korisnik.FirstOrDefault(x => x.Username == User.Identity.Name);

                var preuzeo = db.Preuzeo.FirstOrDefault(x => x.KorisnikID == korisnik.KorisnikID && x.KnjigaID == id);

                var book = db.Knjiga.FirstOrDefault(x => x.KnjigaID == id);

                if (preuzeo == null && book != null)
                {
                    preuzeo = db.Preuzeo.Create();
                    preuzeo.KnjigaID = id;
                    preuzeo.Knjiga = book;
                    preuzeo.Korisnik = korisnik;
                    preuzeo.KorisnikID = korisnik.KorisnikID;
                    preuzeo.VremePreuzimanja = DateTime.Now;

                    db.Preuzeo.Add(preuzeo);

                    db.SaveChanges();
                }

                if (book != null)
                {

                    KnjigaDetails kd = new KnjigaDetails(book, 0);
                    kd.NoviKomentar = new Komentar();
                    kd.NoviKomentar.KnjigaID = book.KnjigaID;

                    return PartialView("_CommentInfo", kd);
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return new EmptyResult();
                }
            }
        }

        [HttpPost]
        public ActionResult VoteUp(int id)
        {
            using (SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel())
            {

                var vu = db.VoteUp.Create();
                vu.KomentarID = id;
                vu.KorisnikID = ((KorisnikZaPrikaz)Session["Korisnik"]).KorisnikId;
                int korid = (int)vu.KorisnikID;

                var Komentar = db.Komentar.FirstOrDefault(x => x.KomentarID == id);
                if (db.VoteUp.FirstOrDefault(x => x.KomentarID == id && x.KorisnikID == vu.KorisnikID) == null)
                {
                    if (db.VoteDown.FirstOrDefault(x => x.KomentarID == id && x.KorisnikID == korid) != null)
                    {
                        VoteDown v = db.VoteDown.FirstOrDefault(x => x.KomentarID == id && x.KorisnikID == korid);
                        db.VoteDown.Remove(v);
                        db.SaveChanges();
                        Komentar.VoteDown = db.VoteDown.Where(x => x.KomentarID == id).Count();
                    }
                    db.VoteUp.Add(vu);
                    db.SaveChanges();

SkolskaBiblioteka/SkolskaBiblioteka/Views/Library/Book.cshtml
@model SkolskaBiblioteka.ViewModels.KnjigaDetails
    @using PagedList;

@using SkolskaBibliotekaDBContext

@{
    ViewBag.Title = "Књига";
}

<div class="container book-container">
    <div class="book-info">
        
        <img class="bookshelf-image" src="~/Images/bookshelf.png"/>
        <img class="book-image" src="@Html.ValueFor(model => model.PicPath)" />

        <div class="book-name">@Html.ValueFor(model => model.Naziv)</div>

        <div>@Model.Autori</div>
        <br/>

        <div id="commentInfo">
            @Html.Partial("_CommentInfo", Model)
        </div>

    </div>
    <div class="book-desc">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque iaculis ultrices urna vitae tempor. Nulla quis lacus erat. Curabitur non rutrum elit. Ut gravida nisl massa, eget eleifend massa ultrices vel. Nunc fermentum lacus neque, a luctus dolor cursus eu. Curabitur eu urna ultricies, sodales justo ac, imperdiet lectus. Aenean sodales venenatis erat rutrum fermentum. Pellentesque molestie efficitur nisi id pretium. Nulla ac ullamcorper nulla, in efficitur diam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent non eros ligula. Phasellus eget augue orci.<br/><br />

        Cras pellentesque lacinia facilisis. Fusce in tempus ex. Aenean nec feugiat urna. Sed pulvinar, dui efficitur faucibus volutpat, ligula neque varius odio, in bibendum ante mi ac odio. Aliquam nisl metus, tincidunt porttitor semper sit amet, fermentum vel neque. Vestibulum eros tellus, imperdiet nec dolor ac, pharetra rhoncus lectus. Nunc malesuada sagittis leo ut porta. Praesent et posuere nunc. Cras aliquet finibus purus, eu eleifend lectus ullamcorper lobortis. Donec vel semper lorem.<br/><br />

        Nunc volutpat pretium nisi, eget fermentum ante imperdiet ac. Sed pellentesque aliquet vulputate. Nullam malesuada mauris ac fringilla cursus. Vivamus convallis consectetur orci, vitae iaculis ante pulvinar at. Quisque commodo scelerisque ipsum eu facilisis. In et enim urna. Donec vel elit justo. Mauris mattis lorem vitae consequat feugiat. Etiam ut enim gravida, placerat urna in, feugiat lorem. Suspendisse dictum lorem nec augue accumsan, non ultricies orci tincidunt. Suspendisse imperdiet purus vitae felis consequat, ac pharetra nunc eleifend. Vivamus sit amet justo accumsan, congue justo ac, tempor diam. Duis nec est at arcu mattis laoreet eu non nibh.<br/><br />

        Integer posuere sollicitudin scelerisque. Sed nec vulputate leo. Ut imperdiet eleifend molestie. Nullam pharetra at risus eu venenatis. Praesent id eros eget urna vehicula ornare eget a magna. Praesent ut enim accumsan, laoreet mi id, sollicitudin massa. Aenean eros est, lacinia sed erat id, placerat iaculis quam. Pellentesque rutrum dignissim lectus ut ultricies.<br /><br />
        @Html.ValueFor(model => model.Opis)
    </div>
    
    <div style="clear:both;"></div>
    <hr/>
    <div class="comment-container">
        <div class="comment-heading"><h4>Komentari:</h4></div>
        <div>

            @Html.Partial("_AddComment", Model.NoviKomentar)

            <div id="komentari">
                @Html.Partial("_Komentari", Model)
            </div>
        </div>
    </div>
</div>

SkolskaBiblioteka/SkolskaBiblioteka/Views/Library/Index.cshtml
@model IEnumerable<SkolskaBibliotekaDBContext.Knjiga>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PicPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Izdavac.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Signatura.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UDK)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ISBN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumIzdavanja)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PDFPath)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PicPath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Izdavac.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Signatura.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UDK)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PicPath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumIzdavanja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PDFPath)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.KnjigaID }) |
                @Html.ActionLink("Details", "Details", new { id = item.KnjigaID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.KnjigaID })
            </td>
        </tr>
    }

</table>

SkolskaBiblioteka/SkolskaBiblioteka/Views/Library/Report.cshtml
@model SkolskaBiblioteka.ViewModels.ReportZaPrikaz

@using SkolskaBiblioteka.ViewModels

@{
    ViewBag.Title = "Пријава коментара";
}

@Styles.Render("~/Content/css")
@Styles.Render("~/Content/themes/css")
@*@Scripts.Render("~/bundles/modernizr")*@
<link href="~/Content/sweetalert.css" rel="stylesheet" />
<link rel="shortcut icon" type="image/ico" href="~/Images/favicon.ico">
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/jquery-ajax")
@Scripts.Render("~/bundles/bootstrap")
<link rel="stylesheet" href="~/Content/font-awesome.min.css" type="text/css" />



<div class="container">
    @Html.Partial("_Komentar", Model.kzp)

    @using (Html.BeginForm("Report", "Library", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()



            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            @Html.Hidden("KomentarId", Model.kzp.KomentarID)


            @Html.Label("Разлог за пријаву:")
            @Html.TextBoxFor(x => x.report.Tekst, new { @class = "form-control", @placeholder = "Превише увредљивих речи, спам.", @type = "search" })
            @Html.ValidationMessageFor(x => x.report.Tekst)


            <input type="submit" value="Пошаљи" class="btn btn-custom" />

    }
</div>

SkolskaBiblioteka/SkolskaBiblioteka/Views/Library/ReportSuccess.cshtml
@{
    ViewBag.Title = "Пријава успешна";
}

@Styles.Render("~/Content/css")
@Styles.Render("~/Content/themes/css")
@*@Scripts.Render("~/bundles/modernizr")*@
<link href="~/Content/sweetalert.css" rel="stylesheet" />

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/jquery-ajax")
@Scripts.Render("~/bundles/bootstrap")

<div class="container">
    <p>Успешно сте пријавили коментар. Хвала на сарадњи.</p>
    <p>Можете затворити овај прозор.</p>

    <button onclick="window.close();" class="btn btn-default">Затвори</button>
</div>

SkolskaBiblioteka/SkolskaBiblioteka/Views/Library/_AddComment.cshtml
@model SkolskaBibliotekaDBContext.Komentar

@using SkolskaBibliotekaDBContext;
@using SkolskaBiblioteka.ViewModels;


@if (Request.IsAuthenticated)
{
    using (Ajax.BeginForm("Book", new AjaxOptions { UpdateTargetId = "komentari", OnSuccess = "CommentAdded()" }))
    {
        KorisnikZaPrikaz kzp = (KorisnikZaPrikaz)Session["Korisnik"];

        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.KnjigaID)
        @Html.HiddenFor(model => model.KorisnikID)
        @Html.HiddenFor(model => model.Knjiga)
        @Html.HiddenFor(model => model.VoteUp)
        @Html.HiddenFor(model => model.VoteDown)

        <div class="row">
            <div class="col-sm-2 col-md-1 col-lg-1 col-xs-3">
                <div class="thumbnail">
                    <img class="thumbnail-pic" src="@Url.Content("~" + kzp.PicPath)" />
                </div>
            </div>

            <div class="col-sm-10 col-md-11 col-lg-11 col-xs-9">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>@kzp.Ime @kzp.Prezime:</strong>
                    </div>
                    <div class="panel-body">
                        @Html.TextAreaFor(x => x.KomentarText, new { rows = 5, @class = "comment-input", id = "kmntr" })
                    </div>
                    <p>@Html.ValidationMessageFor(x => x.KomentarText, "", new { @class = "text-danger" })</p>
                    <div class="comment-send"><input type="submit" value="Пошаљи" class="btn btn-custom" /></div>
                    <div style="clear:both;"></div>
                </div>
            </div>
        </div>
    }
    <script>
        function RemoveText() {
            $('#kmntr').val('');
        }

        function CommentAdded() {
            RemoveText();
            swal('Обавештење', 'Успешно постављен коментар.', 'success');
        }
    </script>
}

SkolskaBiblioteka/SkolskaBiblioteka/Views/Library/_CommentInfo.cshtml
@model SkolskaBiblioteka.ViewModels.KnjigaDetails

@using SkolskaBibliotekaDBContext

@{
    bool rezervisao = false;

    string duzinaRezervacije = Podesavanja.Get("DuzinaRezervacije");

    if (Request.IsAuthenticated)
    {

        using (SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel())
        {
            int korisnikId = db.Korisnik.FirstOrDefault(y => y.Username == User.Identity.Name).KorisnikID;

            var rez = db.Rezervacije.FirstOrDefault(x => x.KorisnikID == korisnikId && x.KnjigaID == Model.KnjigaId && x.Validna == true);

            if (rez != null)
            {
                rezervisao = true;
            }
        }
    }

}
@if (Model.FizickaKopija)
{
    <div>Слободни примерци: @Html.ValueFor(model => model.SlobodniPrimerci)/@Html.ValueFor(model => model.UkupnoPrimeraka)</div>
    <div>Тренутно читају: @Html.ValueFor(model => model.TrenutnoCitajuCounter)</div>
    <div>Укупно читања: @Html.ValueFor(model => model.CitanoCounter)</div>
}
@if (Model.ElektronskaKopija)
{
    <div>Укупан број преузимања: @Html.ValueFor(model => model.DownloadCounter)</div>
}

<br />
<div>Издавач: @Html.ValueFor(model => model.Izdavac)</div>
<br />

@if (Model.FizickaKopija)
{
    <div class="book-reserve">
        @if (Request.IsAuthenticated)
        {
            if (rezervisao)
            {
                using (Ajax.BeginForm("RemoveReserve", new { id = Model.KnjigaId }, new AjaxOptions { OnSuccess = "swal('Обавештење','Резервација успешно уклоњена.','success')", HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "commentInfo" }))
                {
                    <div class="book-button">
                        <input type="submit" value="Уклони резервацију" class="btn btn-custom" />
                    </div>
                }
            }
            else
            {
                if (Model.SlobodniPrimerci > 0)
                {

                    {
                        using (Ajax.BeginForm("Reserve", new { id = Model.KnjigaId }, new AjaxOptions { OnSuccess = "swal('Обавештење','Успешно сте резервисали књигу. Књига је на стању и можете је узети у року од "+duzinaRezervacije+" дана.','success')", HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "commentInfo" }))
                        {
                            <div class="book-button">
                                <input type="submit" value="Додај резервацију" class="btn btn-custom" />
                            </div>
                        }
                    }
                }
                else
                {
                    using (Ajax.BeginForm("Reserve", new { id = Model.KnjigaId }, new AjaxOptions { OnSuccess = "swal('Обавештење','Успешно сте резервисали књигу. Књига тренутно није на стању. Бићете обавештени када ваш резервисани примерак буде физички доступан.','success')", HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "commentInfo" }))
                    {
                        <div class="book-button">
                            <input type="submit" value="Додај резервацију" class="btn btn-custom" />
                        </div>
                    }
                }
            }
        }
    </div>

}


@if (Model.ElektronskaKopija)
{
    <div class="book-download">
        @if (Request.IsAuthenticated)
        {
            using (Ajax.BeginForm("Download", new { id = Model.KnjigaId }, new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "commentInfo", OnSuccess = "window.open('" + Model.PdfPath + "', '_blank')" }))
            {
                <div class="book-button">
                    <input type="submit" value="Преузми" class="btn btn-custom" />
                </div>
            }
        }
    </div>

}
<div style="clear:both;"></div>

SkolskaBiblioteka/SkolskaBiblioteka/Views/Library/_Komentar.cshtml
@model KomentarZaPrikaz

@using SkolskaBiblioteka.ViewModels
@using System.Globalization

@{
    KorisnikZaPrikaz kzp = (KorisnikZaPrikaz)Session["Korisnik"];

    var cultSr = CultureInfo.GetCultureInfoByIetfLanguageTag("sr-Cyrl-CS");

    string commId = "comm" + Model.KomentarID;
}

@using (Ajax.BeginForm("RemoveComment", new { id = Model.KomentarID }, new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "komentari" }))
{
    <div class="row">
        <div class="col-sm-2 col-md-1 col-lg-1 col-xs-3">
            <div class="thumbnail">
                <a class="comment-link-pic" href="@Url.Action("Profile","Account", new { id=Model.KorisnikID})">
                    <img class="thumbnail-pic" src="@Url.Content("~" + Model.PicPath)" />
                </a>
            </div>
        </div>

        <div class="col-sm-10 col-md-11 col-lg-11 col-xs-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="comment-link-name no-decoration" href="@Url.Action("Profile","Account", new { id=Model.KorisnikID})"><strong>@Model.Ime @Model.Prezime:</strong></a>
                    <br />
                    <div class="top-comment-book-heading-container"><span class="text-muted">@Model.VremeKomentara.ToString("d/M/yyyy/ HH:mm:ss", cultSr)</span></div>
                </div>

                <div class="panel-body">
                    @Model.KomentarText
                </div>
                <div class="panel-footer">
                    @if (Model.AdditionalInfo)
                    {
                        if (kzp != null)
                        {
                            if (kzp.AccessLevels.Min() == 7)
                            {
                                <button type="submit" id="@Model.KomentarID" class="btn-dlt-cmnt">
                                    <span class="glyphicon glyphicon-remove "></span>
                                </button>
                                <p style="margin:0px;">
                                    <strong> Оцена:</strong> @Model.VoteUp @Ajax.ActionLink("👍", "VoteUp", new { id = Model.KomentarID }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = commId }, new { @class = "vote-up" }) @Model.VoteDown
                                    @Ajax.ActionLink("👎", "VoteDown", new { id = Model.KomentarID }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = commId }, new { @class = "vote-down" })
                                </p>
                            }
                            else
                            {
                                if (Model.KorisnikID == kzp.KorisnikId)
                                {
                                    <button type="submit" id="@Model.KomentarID" class="btn-dlt-cmnt">
                                        <span class="glyphicon glyphicon-remove "></span>
                                    </button>
                                    <p style="margin:0px;">
                                        <strong> Оцена:</strong> @Model.VoteUp <span class="vote-up">👍</span> @Model.VoteDown <span class="vote-down">👎</span>
                                    </p>
                                }
                                else
                                {
                                    <p style="margin:0px;">
                                        <strong> Оцена:</strong> @Model.VoteUp @Ajax.ActionLink("👍", "VoteUp", new { id = Model.KomentarID }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = commId }, new { @class = "vote-up" }) @Model.VoteDown
                                        @Ajax.ActionLink("👎", "VoteDown", new { id = Model.KomentarID }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = commId }, new { @class = "vote-down" })
                                        <a title="Пријави" class="lnk-rprt-cmnt" onclick="report('@Url.Action("Report", "Library", new { id = Model.KomentarID })')"><i class="fa fa-flag" aria-hidden="true"></i></a>

                                    </p>
                                }
                            }
                        }
                        else
                        {
                            <p style="margin:0px;">
                                <strong> Оцена:</strong> @Model.VoteUp <span class="vote-up">👍</span> @Model.VoteDown <span class="vote-down">👎</span>
                            </p>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
}







<script src="@Url.Content("~/Scripts/reportWindow.js")"></script>

SkolskaBiblioteka/SkolskaBiblioteka/Views/Library/_Komentari.cshtml
@model KnjigaDetails
@using PagedList.Mvc


@using SkolskaBiblioteka.ViewModels

@if (Model.PlKzp.Count > 0)
{
    <div>
        @foreach (KomentarZaPrikaz k in Model.PlKzp)
        {
            string commId = "comm" + k.KomentarID;
            <div id="@commId">
                @Html.Partial("_Komentar", k)
            </div>
        }
        <br />

        <div class="comment-page">

            Страна @(Model.PlKzp.PageCount < Model.PlKzp.PageNumber ? 0 : Model.PlKzp.PageNumber) од @Model.PlKzp.PageCount

            @Html.PagedListPager(Model.PlKzp, page => Url.Action("ChangePage", new { knjigaId = Model.KnjigaId, p = page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "komentari" }))

            <div style="clear:both;"></div>
        </div>
    </div>
}