SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Controllers/PublisherController.cs
using SkolskaBibliotekaDBContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace SkolskaBiblioteka.Areas.Admin.Controllers
{
    [AdminAuth]
    public class PublisherController : Controller
    {
        SkolskaBibliotekaDBModel db = new SkolskaBibliotekaDBModel();

        // GET: Admin/Publisher
        public ActionResult Index(int? p)
        {
            var izdavaci = db.Izdavac.OrderBy(x => x.IzdavacID);
            if (p <= 0) p = 1;

            ViewBag.PageSize = 10;
            ViewBag.PageNumber = (p ?? 1);
            ViewBag.PageCount = izdavaci.ToPagedList((int)ViewBag.PageNumber, (int)ViewBag.PageSize).PageCount;
            ViewBag.HasPrevious = ((p ?? 1) != 1);
            ViewBag.HasNext = ((p ?? 1) != (int)ViewBag.PageCount);

            return View(izdavaci.ToPagedList((int)ViewBag.PageNumber, (int)ViewBag.PageSize).ToList());
        }

        // GET: Admin/Publisher/Details/5
        public ActionResult Details(int id)
        {
            Izdavac izdavac = db.Izdavac.FirstOrDefault(i => i.IzdavacID == id);

            return View(izdavac);
        }

        // GET: Admin/Publisher/Create
        public ActionResult Create()
        {
            Izdavac izdavac = new Izdavac();

            return View(izdavac);
        }

        // POST: Admin/Publisher/Create
        [HttpPost]
        public ActionResult Create(Izdavac izdavac)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    db.Izdavac.Add(izdavac);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                Izdavac i = new Izdavac();

                return View(i);
            }
        }

        // GET: Admin/Publisher/Edit/5
        public ActionResult Edit(int id)
        {
            Izdavac izdavac = db.Izdavac.FirstOrDefault(i => i.IzdavacID == id);

            return View(izdavac);
        }

        // POST: Admin/Publisher/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Izdavac izdavac)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    Izdavac i = db.Izdavac.FirstOrDefault(x => x.IzdavacID == id);
                    i.Naziv = izdavac.Naziv;

                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                Izdavac i = new Izdavac();

                return View(i);
            }
        }

        // GET: Admin/Publisher/Delete/5
        public ActionResult Delete(int id)
        {
            Izdavac izdavac = db.Izdavac.FirstOrDefault(i => i.IzdavacID == id);

            return View(izdavac);
        }

        // POST: Admin/Publisher/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection data)
        {
            try
            {
                Izdavac izdavac = db.Izdavac.FirstOrDefault(i => i.IzdavacID == id);
                if(izdavac != null)
                {
                    db.Izdavac.Remove(izdavac);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Views/Publisher/Create.cshtml
@model SkolskaBibliotekaDBContext.Izdavac

@{
    ViewBag.Title = "Издавач - Додај";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Издавач - Додај</h1>
    </div>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Додај" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад на листу", "Index")
</div>

SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Views/Publisher/Delete.cshtml
@model SkolskaBibliotekaDBContext.Izdavac

@{
    ViewBag.Title = "Издавач - Брисање";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Издавач - Брисање</h1>
    </div>
</div>

<h3>Да ли сте сигурни да желите да обришете овог издавача?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

    </dl>

    @Html.Partial("../Book/Index", Model.Knjiga)

    <br />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Обриши" class="btn btn-default" /> |
            @Html.ActionLink("Назад на листу", "Index")
        </div>
    }
</div>

SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Views/Publisher/Details.cshtml
@model SkolskaBibliotekaDBContext.Izdavac

@{
    ViewBag.Title = "Издавач - Детаљи";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Издавач - Детаљи</h1>
    </div>
</div>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

    </dl>
</div>

@Html.Partial("../Book/Index", Model.Knjiga)

<br />

<p>
    @Html.ActionLink("Измени", "Edit", new { id = Model.IzdavacID }) |
    @Html.ActionLink("Обриши", "Delete", new { id = Model.IzdavacID }) |
    @Html.ActionLink("Назад на листу", "Index")
</p>

SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Views/Publisher/Edit.cshtml
@model SkolskaBibliotekaDBContext.Izdavac

@{
    ViewBag.Title = "Издавач - Измена";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Издавач - Измена</h1>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IzdavacID)

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сачувај" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад на листу", "Index")
</div>

SkolskaBiblioteka/SkolskaBiblioteka/Areas/Admin/Views/Publisher/Index.cshtml
@model IEnumerable<SkolskaBibliotekaDBContext.Izdavac>

@{
    ViewBag.Title = "Издавачи";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Издавачи @Html.ActionLink("Додај", "Create", null, new { @class = "btn btn-default" })</h1>
    </div>
</div>
<div style="overflow:auto;">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Naziv)
                </td>
                <td>
                    @Html.ActionLink("Измени", "Edit", new { id = item.IzdavacID }) |
                    @Html.ActionLink("Детаљи", "Details", new { id = item.IzdavacID }) |
                    @Html.ActionLink("Обриши", "Delete", new { id = item.IzdavacID })
                </td>
            </tr>
        }

    </table>
    </div>
    <nav>
        <ul class="pagination">
            <li class="@((ViewBag.HasPrevious) ? "" : "disabled")">
                <a href="@Url.Action("Index", "Publisher", new { area = "Admin"})?p=@(ViewBag.PageNumber-1)" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for (var i = 1; i <= ViewBag.PageCount; i++)
            {
                if (ViewBag.PageNumber == i)
                {
                    <li class="active"><a href="@Url.Action("Index", "Publisher", new { area = "Admin"})?p=@i">@i <span class="sr-only">(current)</span></a></li>
                }
                else
                {
                    <li><a href="@Url.Action("Index", "Publisher", new { area = "Admin"})?p=@i">@i</a></li>
                }
            }
            <li class="@((ViewBag.HasNext) ? "" : "disabled")">
                <a href="@Url.Action("Index", "Publisher", new { area = "Admin"})?p=@(ViewBag.PageNumber-1)" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>